function net = InitializeTextonNetwork5( input_args )

f=1/100 ;
net.layers = {} ;

net.layers{end+1} = struct('type', 'conv', ...
                           'filters',f*randn(5,5,1,12, 'single'),...
                           'biases', zeros(1,12,'single'), ...
                           'stride', 1, ...     					   
                           'pad', 0) ;
                      
net.layers{end+1} = struct('type', 'relu') 

net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) 
                       
net.layers{end+1} = struct('type', 'conv', ...
                           'filters',f*randn(2,2,12,32, 'single'),...
                           'biases', zeros(1,32,'single'), ...
                           'stride', 1, ...     					   
                           'pad', 0) ;
                      
net.layers{end+1} = struct('type', 'relu') 

net.layers{end+1} = struct('type', 'conv', ...
                           'filters',f*randn(2,2,32,64, 'single'),...
                           'biases', zeros(1,64,'single'), ...
                           'stride', 1, ...     					   
                           'pad', 0) ;
                      
net.layers{end+1} = struct('type', 'relu') 

net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0)                        

net.layers{end+1} = struct('type', 'conv', ...
                           'filters',f*randn(2,2,64,90, 'single'),...
                           'biases', zeros(1,90,'single'), ...
                           'stride', 1, ...     					   
                           'pad', 0) ;  
                       
net.layers{end+1} = struct('type', 'relu') 
                                              
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;   
                       
net.layers{end+1} = struct('type', 'conv', ...
                           'filters',f*randn(2,2,90,128, 'single'),...
                           'biases', zeros(1,128,'single'), ...
                           'stride', 1, ...     					   
                           'pad', 0) ;  
                       
net.layers{end+1} = struct('type', 'relu') 
                                              
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;    
                       
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(2,2,128,25, 'single'),...
                           'biases', zeros(1,25,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;

net.layers{end+1} = struct('type', 'softmaxloss') ;


end